if ~exist('p', 'var')
    run(fullfile(fileparts(mfilename('fullpath')), 'init_parameters.m'));
end

baselineModel = fullfile(p.paths.models, 'PMSM_FOC_Baseline.slx');
optimizationModel = fullfile(p.paths.models, 'PMSM_FOC_Optimization.slx');
cleanup_simulink_artifacts(p);
build_executable_wrapper(baselineModel, 'baseline', p);
build_executable_wrapper(optimizationModel, 'optimization', p);

fid = fopen(fullfile(p.paths.models, 'MODEL_BUILD_NOTES.txt'), 'w', 'n', 'UTF-8');
if fid >= 0
    fprintf(fid, 'Generated by scripts/build_models.m\n');
    fprintf(fid, 'Both models are executable Simulink wrappers around src/pmsm_foc_sfunc.m.\n');
    fprintf(fid, 'The top-level layout was arranged for readability and paper-style presentation.\n');
    fclose(fid);
end

function build_executable_wrapper(modelPath, method, p)
modelName = erase(string(getFileName(modelPath)), ".slx");
modelName = char(modelName);

if bdIsLoaded(modelName)
    try
        set_param(modelName, 'Dirty', 'off');
    catch
    end
    close_system(modelName, 0);
end
if exist(modelPath, 'file') == 2
    delete(modelPath);
end

scenario = struct();
scenario.name = method;
scenario.Tstop = p.Tstop;
scenario.omega_ref = @(t) p.exp.constant.omega_rpm * 2*pi/60;
scenario.load_torque = @(t) p.exp.constant.TL;
assignin('base', 'p', p);
assignin('base', 'scenario', scenario);

new_system(modelName);
set_param(modelName, ...
    'StopTime', num2str(p.Tstop), ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(p.Ts), ...
    'SaveFormat', 'StructureWithTime', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SignalLogging', 'off');

add_block('simulink/User-Defined Functions/Level-2 MATLAB S-Function', [modelName '/PMSM_Engine'], ...
    'FunctionName', 'pmsm_foc_sfunc', ...
    'Parameters', sprintf('p, ''%s'', scenario', method), ...
    'Position', [260 195 400 305]);
add_block('simulink/Signal Routing/Demux', [modelName '/Signal_Bus_Demux'], ...
    'Outputs', num2str(numel(pmsm_foc_output_names())), ...
    'Position', [660 70 690 350]);

names = pmsm_foc_output_names();
for k = 1:numel(names)
    y = 18 + (k - 1) * 15;
    add_block('simulink/Sinks/To Workspace', [modelName '/' names{k}], ...
        'VariableName', [names{k} '_sim'], ...
        'SaveFormat', 'Timeseries', ...
        'Position', [1200 y 1265 y + 12]);
end

add_layout_annotations(modelName, p, method);
add_scenario_annotation(modelName, method);
wire_model(modelName);

save_system(modelName, modelPath);
set_param(modelName, 'Dirty', 'off');
close_system(modelName, 0);

try
    if bdIsLoaded('simulink')
        set_param('simulink', 'Dirty', 'off');
        close_system('simulink', 0);
    end
catch
end
end

function add_layout_annotations(modelName, p, method)
ann = Simulink.Annotation(modelName, sprintf('PMSM FOC Vector Control - %s Model', upperFirst(method)));
ann.Position = [280 10 800 38];
ann.FontSize = 14;
ann.FontWeight = 'bold';

ann = Simulink.Annotation(modelName, sprintf('Executable simulation core | Ts = %.1e s | Tsim = %.1f s', p.Ts, p.Tstop));
ann.Position = [250 38 820 62];
ann.FontSize = 10;

ann = Simulink.Annotation(modelName, 'Controller and plant logic');
ann.Position = [245 110 560 136];
ann.FontSize = 11;
ann.FontWeight = 'bold';

ann = Simulink.Annotation(modelName, 'Optimization and protection states');
ann.Position = [655 110 1045 136];
ann.FontSize = 11;
ann.FontWeight = 'bold';

ann = Simulink.Annotation(modelName, sprintf('Plant: IPMSM dq model | Protection: current limit / voltage limit / freeze logic / slew limit | Method: %s', method));
ann.Position = [210 442 1090 468];
ann.FontSize = 10;

ann = Simulink.Annotation(modelName, sprintf('Reference parameters: Rs=%.2f Ohm, Ld=%.1e H, Lq=%.1e H, psi_f=%.3f Wb, Vdc=%.0f V', ...
    p.Rs, p.Ld, p.Lq, p.psi_f, p.Vdc));
ann.Position = [210 468 1090 492];
ann.FontSize = 9;
end

function add_scenario_annotation(modelName, method)
ann = Simulink.Annotation(modelName, sprintf('Scenario inputs are supplied from workspace struct p/scenario.\nMethod tag: %s', method));
ann.Position = [40 150 240 250];
ann.FontSize = 10;
end

function wire_model(modelName)
add_line(modelName, 'PMSM_Engine/1', 'Signal_Bus_Demux/1');

names = pmsm_foc_output_names();
for k = 1:numel(names)
    add_line(modelName, sprintf('Signal_Bus_Demux/%d', k), [names{k} '/1']);
end
end

function s = upperFirst(str)
if isempty(str)
    s = str;
else
    s = [upper(str(1)) str(2:end)];
end
end

function name = getFileName(path)
[~, name, ext] = fileparts(path);
name = [name ext];
end
