function names = pmsm_foc_output_names()
%PMSM_FOC_OUTPUT_NAMES Ordered signal names exported by the Simulink wrapper.

names = {'omega_m', 'omega_rpm', 'id', 'iq', 'id_ref', 'iq_ref', ...
    'ud', 'uq', 'us', 'is', 'Te', 'Pin', 'Pin_lpf', 'Pout', 'eta', ...
    'speed_error', 'perturbation', 'P_ac', 'demod_signal', 'g_hat', ...
    'id_bar', 'id_bar_before', 'steady_flag', 'optimizer_enable', ...
    'freeze_state', 'projection_active', 'current_saturated', ...
    'voltage_saturated', 'dPin_dt'};
end
