function names = pmsm_foc_output_names()
%PMSM_FOC_OUTPUT_NAMES Ordered signal names exported by the Simulink wrapper.

names = {'omega_m', 'omega_rpm', 'id', 'iq', 'id_ref', 'iq_ref', ...
    'Pin', 'Pout', 'eta', 'g_hat', 'id_bar', 'steady_flag', ...
    'optimizer_enable', 'freeze_state', 'projection_active', ...
    'current_saturated', 'voltage_saturated', 'Te', 'us', 'is'};
end
